# Generated by Django 5.0.14 on 2026-02-26 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('profile_update', 'Profile Updated'), ('role_change', 'Role Changed'), ('password_change', 'Password Changed'), ('password_reset', 'Password Reset'), ('account_suspend', 'Account Suspended'), ('account_activate', 'Account Activated'), ('details_edit', 'Details Edited'), ('admin_action', 'Admin Action')], max_length=50)),
                ('description', models.TextField(blank=True, help_text='Details about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/Client information')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='JSON of what changed')),
                ('admin_user', models.ForeignKey(blank=True, help_text='Admin who performed the action (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_log', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='users_activ_user_id_8a5363_idx'), models.Index(fields=['action', '-timestamp'], name='users_activ_action_04c071_idx')],
            },
        ),
    ]
