# Generated by Django 4.1.3 on 2026-04-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_complete',
            field=models.BooleanField(default=False, help_text='Indicates whether user has completed their profile setup (required for Google OAuth users)'),
        ),
    ]
