# Generated by Django 4.1.3 on 2026-05-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_profile_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('rider', 'Rider'), ('admin', 'Admin'), ('staff', 'Staff'), ('washer', 'Washer'), ('folder', 'Folder'), ('fumigator', 'Fumigator')], default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff_type',
            field=models.CharField(choices=[('general', 'General Staff'), ('washer', 'Washer'), ('folder', 'Folder'), ('fumigator', 'Fumigator')], default='general', help_text='Type of staff: General, Washer, or Folder', max_length=20),
        ),
    ]
