# Generated by Django 5.0.14 on 2026-02-22 17:33

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def create_categories_from_old_data(apps, schema_editor):
    """Create ServiceCategory records from the old category field data."""
    Service = apps.get_model('services', 'Service')
    ServiceCategory = apps.get_model('services', 'ServiceCategory')
    
    # Get all unique category values from existing services
    category_choices = [
        'laundry',
        'duvet',
        'carpet',
        'house',
        'fumigation',
        'installation',
    ]
    
    # Create categories
    category_map = {}
    for cat in category_choices:
        # Convert category names to proper format
        display_name = cat.replace('_', ' ').title()
        if cat == 'duvet':
            display_name = 'Duvet Cleaning'
        elif cat == 'carpet':
            display_name = 'Carpet Cleaning'
        elif cat == 'house':
            display_name = 'House Cleaning'
        elif cat == 'installation':
            display_name = 'TV Mounting & Hot Shower Installation'
        
        obj, created = ServiceCategory.objects.get_or_create(
            name=display_name,
            defaults={
                'slug': slugify(display_name),
                'description': '',
                'is_active': True
            }
        )
        category_map[cat] = obj
    
    # Update services to use the new ForeignKey
    for service in Service.objects.all():
        if service.category_name and service.category_name in category_map:
            service.category = category_map[service.category_name]
            service.save()


def reverse_function(apps, schema_editor):
    ServiceCategory = apps.get_model('services', 'ServiceCategory')
    ServiceCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_image'),
    ]

    operations = [
        # Step 1: Create ServiceCategory model
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly name (auto-generated)', unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive categories will be hidden from the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['name'],
            },
        ),
        # Step 2: Add new fields to Service
        migrations.AddField(
            model_name='service',
            name='category_name',
            field=models.CharField(blank=True, help_text='Legacy: kept for migration purposes', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='new_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive services will be hidden from the website'),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # Step 3: Copy old category data to category_name before converting
        migrations.RunPython(
            lambda apps, schema_editor: None,  # Will just prepare data
            lambda apps, schema_editor: None
        ),
        # Step 4: Create categories and migrate data
        migrations.RunPython(create_categories_from_old_data, reverse_function),
        # Step 5: Rename new_category to category
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='new_category',
            new_name='category',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['category', 'name']},
        ),
    ]
