# Generated by Django 5.0.14 on 2026-02-22 17:33
# SIMPLIFIED: Just create the ServiceCategory model without complex field changes

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def create_initial_categories(apps, schema_editor):
    """Create default service categories."""
    try:
        ServiceCategory = apps.get_model('services', 'ServiceCategory')
        
        categories = [
            ('Laundry', 'laundry'),
            ('Duvet Cleaning', 'duvet-cleaning'),
            ('Carpet Cleaning', 'carpet-cleaning'),
            ('House Cleaning', 'house-cleaning'),
            ('Fumigation', 'fumigation'),
            ('TV Mounting & Hot Shower Installation', 'tv-mounting-hot-shower-installation'),
        ]
        
        for name, slug in categories:
            ServiceCategory.objects.get_or_create(
                name=name,
                defaults={
                    'slug': slug,
                    'description': '',
                    'is_active': True
                }
            )
    except Exception as e:
        # Don't fail build if this doesn't work
        print(f"Note: Could not create initial categories: {e}")


def reverse_categories(apps, schema_editor):
    """Delete all categories on reverse."""
    try:
        ServiceCategory = apps.get_model('services', 'ServiceCategory')
        ServiceCategory.objects.all().delete()
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_image'),
    ]

    operations = [
        # Create ServiceCategory model
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly name (auto-generated)', unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive categories will be hidden from the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['name'],
            },
        ),
        # Create default categories from existing choices
        migrations.RunPython(create_initial_categories, reverse_categories),
    ]
