# Generated by Django 4.1.3 on 2026-04-05 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicecategory_alter_service_options_and_more'),
    ]

    operations = [
    ]
