# Generated by Django 4.1.3 on 2026-04-05 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_options_service_category_name_and_more'),
    ]

    operations = [
    ]
