# Generated by Django 4.1.3 on 2026-04-05 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0016_add_washer_folder_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='folder_items',
            field=models.IntegerField(blank=True, help_text='Number of items recorded by folder', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='folder_notes',
            field=models.TextField(blank=True, help_text='Notes/description recorded by folder', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='folder_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual price recorded by folder', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='folder_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight (kg) recorded by folder', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fumigated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when order was fumigated', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fumigator',
            field=models.ForeignKey(blank=True, help_text='Staff member who fumigated the order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fumigated_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='fumigator_items',
            field=models.IntegerField(blank=True, help_text='Number of items recorded by fumigator', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fumigator_notes',
            field=models.TextField(blank=True, help_text='Notes/description recorded by fumigator', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fumigator_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual price recorded by fumigator', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fumigator_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight (kg) recorded by fumigator', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_items',
            field=models.IntegerField(blank=True, help_text='Number of items recorded by rider', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_notes',
            field=models.TextField(blank=True, help_text='Notes/description recorded by rider during delivery', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual price recorded by rider', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight (kg) recorded by rider', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='washer_items',
            field=models.IntegerField(blank=True, help_text='Number of items recorded by washer', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='washer_notes',
            field=models.TextField(blank=True, help_text='Notes/description recorded by washer', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='washer_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual price recorded by washer', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='washer_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight (kg) recorded by washer', max_digits=6, null=True),
        ),
    ]
