# Generated by Django 4.1.3 on 2026-05-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_folder_items_order_folder_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mpesa', 'M-Pesa'), ('card', 'Card'), ('bnpl', 'Buy Now Pay Later'), ('cash', 'Cash')], help_text='Payment method used for this order', max_length=50, null=True),
        ),
    ]
